services:
  - type: web
    name: healfund-backend
    env: node
    rootDir: backend
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: USER_FRONTEND_URL
        value: https://healfund-user.onrender.com
      - key: ADMIN_FRONTEND_URL
        value: https://healfund-admin.onrender.com
      - key: EMAIL_SERVICE
        value: gmail
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: EMAIL_FROM
        value: HealFundET@gmail.com

  - type: static site
    name: healfund-user
    rootDir: user frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://healfund-backend.onrender.com/api

  - type: static site
    name: healfund-admin
    rootDir: admin frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://healfund-backend.onrender.com/api
