// In-memory data store for HealFund backend

export const dataStore = {
  hospitals: [
    {
      id: 'HOSP-001',
      name: 'Zewditu Memorial Hospital',
      location: 'Addis Ababa, Kirkos',
      level: 'Tertiary / Referral Hospital',
      verified: true,
      departments: ['Cardiology', 'General Surgery', 'Pediatrics', 'Oncology', 'Orthopedics', 'Internal Medicine', 'Neurology'],
      phone: '+251-11-551-8085',
    },
  ],

  appointments: [
    {
      id: 'APT-1001',
      patientId: 'HF-0247',
      patientName: 'Ahmed Kamara',
      hospitalName: 'Zewditu Memorial Hospital',
      doctorName: 'Dr. M. Worku',
      department: 'Cardiology',
      datetime: '2026-08-25T10:00:00Z',
      status: 'Confirmed',
      queueToken: 'C-023',
    },
    {
      id: 'APT-1002',
      patientId: 'HF-0247',
      patientName: 'Ahmed Kamara',
      hospitalName: 'Zewditu Memorial Hospital',
      doctorName: 'Dr. S. Alemu',
      department: 'Follow-up Clinic',
      datetime: '2026-09-02T14:30:00Z',
      status: 'Pending',
      queueToken: 'C-048',
    },
  ],

  queue: [
    {
      token: 'C-023',
      patientId: 'HF-0247',
      patientName: 'Ahmed Kamara',
      department: 'Cardiology Clinic (Room 104)',
      assignedDoctor: 'Dr. M. Worku',
      estimatedTime: '2026-08-25 10:00 AM',
      status: 'Scheduled',
      urgency: 'High',
      requiredDocuments: ['Medical Records', 'Patient ID Card', 'Lab Reports'],
    },
    {
      token: 'C-024',
      patientId: 'HF-0298',
      patientName: 'Solomon Haile',
      department: 'Cardiology Clinic (Room 104)',
      assignedDoctor: 'Dr. M. Worku',
      estimatedTime: '2026-08-25 10:30 AM',
      status: 'Waiting',
      urgency: 'Medium',
      requiredDocuments: ['Medical Records', 'Patient ID Card'],
    },
  ],

  financialCases: [
    {
      id: 'CASE-2026-8801',
      patientId: 'HF-0247',
      patientName: 'Ahmed Kamara',
      age: 42,
      location: 'Addis Ababa, Lideta',
      diagnosis: 'Severe Hypertensive Heart Failure & Valve Procedure',
      verifyingHospital: 'Zewditu Memorial Hospital',
      verifiedByDoctor: 'Dr. M. Worku (Head of Cardiology)',
      verificationStage1: 'Medical Records Verified at Zewditu Memorial Hospital',
      verificationStage2: 'Financial Need Verified by Zewditu Social Work Unit',
      targetAmount: 85000,
      raisedAmount: 54200,
      currency: 'ETB',
      description: 'Ahmed is a 42-year-old father of three suffering from acute hypertensive heart failure requiring specialized interventional cardiac care and medication support at Zewditu Memorial Hospital. His family cannot afford the specialized surgical supply costs.',
      status: 'Active',
      donorsCount: 142,
      createdAt: '2026-08-11T16:00:00Z',
    },
    {
      id: 'CASE-2026-8805',
      patientId: 'HF-0389',
      patientName: 'Tigist Mersha',
      age: 8,
      location: 'Adama, Oromia',
      diagnosis: 'Pediatric Ventricular Septal Defect Repair',
      verifyingHospital: 'Zewditu Memorial Hospital',
      verifiedByDoctor: 'Dr. Abera Tekle',
      verificationStage1: 'Medical Records Verified at Zewditu Memorial Hospital',
      verificationStage2: 'Financial Assistance Approved',
      targetAmount: 120000,
      raisedAmount: 98500,
      currency: 'ETB',
      description: 'Tigist is an 8-year-old student referred for congenital heart defect corrective surgery. The medical team at Zewditu has cleared her for surgery upon funding verification.',
      status: 'Active',
      donorsCount: 310,
      createdAt: '2026-08-05T10:00:00Z',
    },
  ],

  users: {
    'you@example.com': {
      name: 'Ahmed Kamara',
      email: 'you@example.com',
      password: 'password123',
      age: 42,
      gender: 'Male',
      location: 'Addis Ababa, Lideta',
      patientId: 'HF-0247',
      status: 'Verified',
      registered: '12 Aug 2026',
    },
    'staff@zewditu.gov.et': {
      name: 'Dr. Tadesse Bekele',
      email: 'staff@zewditu.gov.et',
      password: 'hospital123',
      hospitalId: 'HOSP-001',
      hospitalName: 'Zewditu Memorial Hospital',
      role: 'Hospital Officer',
    },
    'HealFund2006@gmail.com': {
      name: 'HealFund Owner',
      email: 'HealFund2006@gmail.com',
      password: 'healFund@2026',
      hospitalId: 'HOSP-001',
      hospitalName: 'Zewditu Memorial Hospital',
      role: 'Head of Department',
    },
  },

  messages: [
    {
      id: 'MSG-1001',
      name: 'Selamawit Desta',
      contact: 'selam.desta@gmail.com',
      category: 'Medical File Verification',
      message: 'Hello, I uploaded my medical lab results and doctor certificate yesterday for Zewditu Memorial Hospital. Could you please check the verification status so I can confirm my appointment?',
      status: 'Unread',
      createdAt: '2026-08-15T09:20:00Z',
    },
    {
      id: 'MSG-1002',
      name: 'Kassahun Belay',
      contact: 'kassahun.b@ethionet.et',
      category: 'Medical File Verification',
      message: 'Inquiring about medical file review timeline at Zewditu Memorial Hospital Cardiology clinic.',
      status: 'Read',
      createdAt: '2026-08-14T14:45:00Z',
    },
    {
      id: 'MSG-1003',
      name: 'Genet Wolde',
      contact: 'genet.w@yahoo.com',
      category: 'Community Agent',
      message: 'My elderly mother cannot travel easily to the hospital or use a smartphone. We would appreciate a community health field agent visit in Kirkos / Lideta area.',
      status: 'Unread',
      createdAt: '2026-08-15T11:10:00Z',
    },
  ],
};
