// In-memory data store for HealFund backend

export const dataStore = {
  hospitals: [
    {
      id: 'HOSP-001',
      name: 'Zewditu Memorial Hospital',
      location: 'Addis Ababa, Kirkos',
      level: 'Tertiary / Referral Hospital',
      verified: true,
      departments: ['Cardiology', 'General Surgery', 'Pediatrics', 'Oncology', 'Orthopedics', 'Internal Medicine', 'Neurology'],
      phone: '+251-11-551-8085',
    },
    {
      id: 'HOSP-002',
      name: 'Lideta Health Center',
      location: 'Addis Ababa, Lideta',
      level: 'Primary Health Care Unit',
      verified: true,
      departments: ['Outpatient', 'Emergency Care', 'Maternal & Child Health', 'Basic Diagnostics'],
      phone: '+251-11-553-2211',
    },
    {
      id: 'HOSP-003',
      name: "St. Paul's Hospital Millennium Medical College",
      location: 'Addis Ababa, Gulele',
      level: 'Specialized Referral Hospital',
      verified: true,
      departments: ['Nephrology', 'Cardiology', 'Surgery', 'Transplant Center'],
      phone: '+251-11-275-0125',
    },
    {
      id: 'HOSP-004',
      name: 'Tikur Anbessa (Black Lion) Hospital',
      location: 'Addis Ababa, Lideta',
      level: 'National Specialized Hospital',
      verified: true,
      departments: ['Oncology', 'Radiotherapy', 'Pediatric Surgery', 'Trauma'],
      phone: '+251-11-551-1211',
    },
    {
      id: 'HOSP-005',
      name: 'Yekatit 12 Hospital Medical College',
      location: 'Addis Ababa, Arada',
      level: 'General & Referral Hospital',
      verified: true,
      departments: ['Burn Unit', 'Plastic Surgery', 'General Medicine'],
      phone: '+251-11-123-4567',
    },
  ],

  referrals: [
    {
      id: 'REF-2026-00452',
      patientName: 'Ahmed Kamara',
      patientId: 'HF-0247',
      patientAge: 42,
      patientGender: 'Male',
      patientLocation: 'Addis Ababa, Lideta',
      sendingHospitalId: 'HOSP-002',
      sendingHospitalName: 'Lideta Health Center',
      sendingDoctor: 'Dr. Tadesse Bekele',
      receivingHospitalId: 'HOSP-001',
      receivingHospitalName: 'Zewditu Memorial Hospital',
      department: 'Cardiology',
      urgency: 'High',
      reasonForReferral: 'Severe hypertensive heart failure with pulmonary congestion requiring specialized echocardiography and ICU monitoring.',
      clinicalSummary: 'Patient presented with shortness of breath (NYHA Class III) and blood pressure 180/110 mmHg. Basic ECG completed at primary center. Needs urgent cardiology consultation.',
      documents: ['ECG_Report_0247.pdf', 'Lab_Results_Lideta.pdf'],
      contactPhone: '+251921198350',
      status: 'Accepted',
      createdAt: '2026-08-10T09:30:00Z',
      acceptedAt: '2026-08-11T14:15:00Z',
      assignedDoctor: 'Dr. M. Worku',
      queueToken: 'C-023',
      appointmentTime: '2026-08-25T10:00:00Z',
    },
    {
      id: 'REF-2026-00489',
      patientName: 'Bethlehem Alemu',
      patientId: 'HF-0312',
      patientAge: 29,
      patientGender: 'Female',
      patientLocation: 'Addis Ababa, Bole',
      sendingHospitalId: 'HOSP-002',
      sendingHospitalName: 'Lideta Health Center',
      sendingDoctor: 'Dr. Helen Wolde',
      receivingHospitalId: 'HOSP-001',
      receivingHospitalName: 'Zewditu Memorial Hospital',
      department: 'General Surgery',
      urgency: 'Medium',
      reasonForReferral: 'Symptomatic cholelithiasis with recurrent biliary colic.',
      clinicalSummary: 'Ultrasound confirmed gallstones. Recommended elective laparoscopic cholecystectomy.',
      documents: ['Ultrasound_Report.pdf'],
      contactPhone: '+251911445566',
      status: 'Pending Review',
      createdAt: '2026-08-12T11:00:00Z',
    },
  ],

  appointments: [
    {
      id: 'APT-1001',
      patientId: 'HF-0247',
      patientName: 'Ahmed Kamara',
      hospitalName: 'Zewditu Memorial Hospital',
      doctorName: 'Dr. M. Worku',
      department: 'Cardiology',
      datetime: '2026-08-25T10:00:00Z',
      status: 'Confirmed',
      queueToken: 'C-023',
      referralId: 'REF-2026-00452',
    },
    {
      id: 'APT-1002',
      patientId: 'HF-0247',
      patientName: 'Ahmed Kamara',
      hospitalName: 'Zewditu Memorial Hospital',
      doctorName: 'Dr. S. Alemu',
      department: 'Follow-up Clinic',
      datetime: '2026-09-02T14:30:00Z',
      status: 'Pending',
      queueToken: 'C-048',
    },
  ],

  queue: [
    {
      token: 'C-023',
      patientId: 'HF-0247',
      patientName: 'Ahmed Kamara',
      department: 'Cardiology Clinic (Room 104)',
      assignedDoctor: 'Dr. M. Worku',
      estimatedTime: '2026-08-25 10:00 AM',
      status: 'Scheduled',
      urgency: 'High',
      requiredDocuments: ['Referral Letter REF-2026-00452', 'ID / QR Card', 'Lab Reports'],
    },
    {
      token: 'C-024',
      patientId: 'HF-0298',
      patientName: 'Solomon Haile',
      department: 'Cardiology Clinic (Room 104)',
      assignedDoctor: 'Dr. M. Worku',
      estimatedTime: '2026-08-25 10:30 AM',
      status: 'Waiting',
      urgency: 'Medium',
      requiredDocuments: ['Referral Letter', 'ID / QR Card'],
    },
  ],

  financialCases: [
    {
      id: 'CASE-2026-8801',
      patientId: 'HF-0247',
      patientName: 'Ahmed Kamara',
      age: 42,
      location: 'Addis Ababa, Lideta',
      diagnosis: 'Severe Hypertensive Heart Failure & Valve Procedure',
      referralId: 'REF-2026-00452',
      verifyingHospital: 'Zewditu Memorial Hospital',
      verifiedByDoctor: 'Dr. M. Worku (Head of Cardiology)',
      verificationStage1: 'Referral Verified (Lideta HC → Zewditu)',
      verificationStage2: 'Financial Need Verified by Zewditu Social Work Unit',
      targetAmount: 85000, // ETB
      raisedAmount: 54200, // ETB
      currency: 'ETB',
      description: 'Ahmed is a 42-year-old father of three suffering from acute hypertensive heart failure requiring specialized interventional cardiac care and medication support at Zewditu Memorial Hospital. His family cannot afford the specialized surgical supply costs.',
      status: 'Active',
      donorsCount: 142,
      hospitalBadgeUrl: '/badges/zewditu_verified.png',
      createdAt: '2026-08-11T16:00:00Z',
    },
    {
      id: 'CASE-2026-8805',
      patientId: 'HF-0389',
      patientName: 'Tigist Mersha',
      age: 8,
      location: 'Adama, Oromia',
      diagnosis: 'Pediatric Ventricular Septal Defect Repair',
      referralId: 'REF-2026-00311',
      verifyingHospital: 'Zewditu Memorial Hospital',
      verifiedByDoctor: 'Dr. Abera Tekle',
      verificationStage1: 'Referral Verified (Adama Hospital → Zewditu)',
      verificationStage2: 'Financial Assistance Approved',
      targetAmount: 120000,
      raisedAmount: 98500,
      currency: 'ETB',
      description: 'Tigist is an 8-year-old student referred from Adama for congenital heart defect corrective surgery. The medical team at Zewditu has cleared her for surgery upon funding verification.',
      status: 'Active',
      donorsCount: 310,
      createdAt: '2026-08-05T10:00:00Z',
    },
  ],

  users: {
    'you@example.com': {
      name: 'Ahmed Kamara',
      email: 'you@example.com',
      password: 'password123',
      age: 42,
      gender: 'Male',
      location: 'Addis Ababa, Lideta',
      patientId: 'HF-0247',
      status: 'Verified',
      registered: '12 Aug 2026',
    },
    'staff@lidetahc.gov.et': {
      name: 'Dr. Tadesse Bekele',
      email: 'staff@lidetahc.gov.et',
      password: 'hospital123',
      hospitalId: 'HOSP-002',
      hospitalName: 'Lideta Health Center',
      role: 'Hospital Officer',
    },
    'admin@zewditu.gov.et': {
      name: 'Dr. M. Worku',
      email: 'admin@zewditu.gov.et',
      password: 'admin123',
      hospitalId: 'HOSP-001',
      hospitalName: 'Zewditu Memorial Hospital',
      role: 'Head of Department',
    },
  },

  messages: [
    {
      id: 'MSG-1001',
      name: 'Selamawit Desta',
      contact: 'selam.desta@gmail.com',
      category: 'Medical File Verification',
      message: 'Hello, I uploaded my medical lab results and doctor certificate yesterday from Lideta clinic. Could you please check the verification status so I can confirm my referral appointment?',
      status: 'Unread',
      createdAt: '2026-08-15T09:20:00Z',
    },
    {
      id: 'MSG-1002',
      name: 'Kassahun Belay',
      contact: 'kassahun.b@ethionet.et',
      category: 'Hospital Referral',
      message: 'Inquiring about referral transfer timeline from Tikur Anbessa to Zewditu Memorial Hospital Cardiology clinic.',
      status: 'Read',
      createdAt: '2026-08-14T14:45:00Z',
    },
    {
      id: 'MSG-1003',
      name: 'Genet Wolde',
      contact: 'genet.w@yahoo.com',
      category: 'Community Agent',
      message: 'My elderly mother cannot travel easily to the hospital or use a smartphone. We would appreciate a community health field agent visit in Lideta area.',
      status: 'Unread',
      createdAt: '2026-08-15T11:10:00Z',
    },
  ],

  // System admins (separate from hospital users)
  admins: {
    'superadmin@healfund.et': {
      name: 'HealFund Administrator',
      email: 'superadmin@healfund.et',
      password: 'healfund@admin2026',
      role: 'superadmin',
      avatar: 'H',
    },
  },

  // Patient uploaded documents — only admin can view & verify
  patientDocuments: [
    {
      id: 'DOC-0001',
      patientId: 'HF-0247',
      patientName: 'Ahmed Kamara',
      originalName: 'ECG_Report_0247.pdf',
      filename: 'sample-ecg-report.pdf',
      size: '1.20 MB',
      type: 'pdf',
      category: 'Privacy & Diagnostic Report',
      isPrivacyDocument: true,
      uploadDate: '2026-08-12T08:30:00Z',
      status: 'Pending Verification', // 'Pending Verification' | 'Verified' | 'Rejected'
      adminNote: '',
      queueToken: null,
    },
    {
      id: 'DOC-0002',
      patientId: 'HF-0247',
      patientName: 'Ahmed Kamara',
      originalName: 'Lab_Results_Lideta.pdf',
      filename: 'sample-lab-results.pdf',
      size: '0.85 MB',
      type: 'pdf',
      category: 'Confidential Health File',
      isPrivacyDocument: true,
      uploadDate: '2026-08-12T08:35:00Z',
      status: 'Verified',
      adminNote: 'Lab values confirmed by Admin. Added to Zewditu Cardiology waiting list.',
      queueToken: 'C-023',
    },
    {
      id: 'DOC-0003',
      patientId: 'HF-0312',
      patientName: 'Bethlehem Alemu',
      originalName: 'Ultrasound_Report.pdf',
      filename: 'sample-ultrasound.pdf',
      size: '2.10 MB',
      type: 'pdf',
      category: 'Privacy & Imaging Record',
      isPrivacyDocument: true,
      uploadDate: '2026-08-13T10:00:00Z',
      status: 'Pending Verification',
      adminNote: '',
      queueToken: null,
    },
  ],

  // Activity log for audit trail
  activityLog: [
    {
      id: 'LOG-001',
      action: 'Referral Accepted',
      detail: 'REF-2026-00452 accepted → Zewditu Memorial Hospital',
      actor: 'Dr. M. Worku',
      timestamp: '2026-08-11T14:15:00Z',
    },
    {
      id: 'LOG-002',
      action: 'Financial Case Created',
      detail: 'CASE-2026-8801 opened for Ahmed Kamara',
      actor: 'System',
      timestamp: '2026-08-11T16:00:00Z',
    },
    {
      id: 'LOG-003',
      action: 'Donation Received',
      detail: 'CASE-2026-8801 received 500 ETB donation',
      actor: 'Anonymous Donor',
      timestamp: '2026-08-12T09:20:00Z',
    },
  ],
};
