// In-memory data store for HealFund backend

export const dataStore = {
  hospitals: [
    {
      id: 'HOSP-001',
      name: 'Zewditu Memorial Hospital',
      location: 'Addis Ababa, Kirkos',
      level: 'Tertiary / Referral Hospital',
      verified: true,
      departments: ['Cardiology', 'General Surgery', 'Pediatrics', 'Oncology', 'Orthopedics', 'Internal Medicine', 'Neurology'],
      phone: '+251-11-551-8085',
    },
  ],

  appointments: [
    {
      id: 'APT-1001',
      patientId: 'HF-0247',
      bookedByUserId: 'you@example.com',
      isForSelf: true,
      patientName: 'Ahmed Kamara',
      patientAge: 42,
      patientGender: 'Male',
      relationship: 'Self',
      urgency: 'High',
      disease: 'Severe chest discomfort and chronic hypertension symptoms requiring cardiology assessment',
      preferredDepartment: 'Cardiology',
      hospitalName: 'Zewditu Memorial Hospital',
      assignedDoctor: 'Dr. M. Worku',
      assignedDepartment: 'Cardiology Clinic',
      assignedRoom: 'Room 104',
      status: 'Approved',
      queueToken: 'C-023',
      estimatedTime: '2026-08-25T09:00:00.000Z',
      requestedAt: '2026-08-20T08:15:00.000Z',
      reviewedAt: '2026-08-20T08:45:00.000Z',
      supportingFiles: [
        {
          id: 'DOC-8812',
          originalName: 'Echocardiogram_Report_Ahmed.pdf',
          filename: '1724140000000-Echocardiogram_Report_Ahmed.pdf',
          size: '1.85 MB',
          type: 'pdf',
          uploadDate: '2026-08-20T08:15:00.000Z',
        },
      ],
      requestedDocuments: [],
      adminNote: 'Approved. Patient assigned to Cardiology Clinic Room 104.',
    },
    {
      id: 'APT-1002',
      patientId: 'HF-0247',
      bookedByUserId: 'you@example.com',
      isForSelf: false,
      patientName: 'Fatima Kamara',
      patientAge: 12,
      patientGender: 'Female',
      relationship: 'Daughter',
      urgency: 'Medium',
      disease: 'Persistent high fever, respiratory cough, and fatigue for past 4 days',
      preferredDepartment: 'Pediatrics',
      hospitalName: 'Zewditu Memorial Hospital',
      assignedDoctor: '',
      assignedDepartment: '',
      assignedRoom: '',
      status: 'Pending Review',
      queueToken: '',
      estimatedTime: '',
      requestedAt: '2026-08-20T09:30:00.000Z',
      reviewedAt: '',
      supportingFiles: [
        {
          id: 'DOC-8815',
          originalName: 'Pediatric_Referral_Letter.pdf',
          filename: '1724142000000-Pediatric_Referral_Letter.pdf',
          size: '1.12 MB',
          type: 'pdf',
          uploadDate: '2026-08-20T09:30:00.000Z',
        },
      ],
      requestedDocuments: [],
      adminNote: '',
    },
    {
      id: 'APT-1003',
      patientId: 'HF-0312',
      bookedByUserId: 'selam@example.com',
      isForSelf: true,
      patientName: 'Selamawit Tadesse',
      patientAge: 35,
      patientGender: 'Female',
      relationship: 'Self',
      urgency: 'Emergency',
      disease: 'Acute abdominal pain with vomiting and suspicion of appendicitis',
      preferredDepartment: 'General Surgery',
      hospitalName: 'Zewditu Memorial Hospital',
      assignedDoctor: 'Dr. Tadesse Bekele',
      assignedDepartment: 'General Surgery Clinic',
      assignedRoom: 'Room 202',
      status: 'Approved',
      queueToken: 'C-024',
      estimatedTime: '2026-08-25T09:10:00.000Z',
      requestedAt: '2026-08-20T07:00:00.000Z',
      reviewedAt: '2026-08-20T07:15:00.000Z',
      supportingFiles: [],
      requestedDocuments: [],
      adminNote: 'Priority surgical consultation scheduled.',
    },
    {
      id: 'APT-1004',
      patientId: 'HF-0388',
      bookedByUserId: 'kassahun@example.com',
      isForSelf: false,
      patientName: 'Abebe Belay',
      patientAge: 68,
      patientGender: 'Male',
      relationship: 'Father',
      urgency: 'Medium',
      disease: 'Post-stroke motor rehabilitation consultation and orthopedic review',
      preferredDepartment: 'Orthopedics',
      hospitalName: 'Zewditu Memorial Hospital',
      assignedDoctor: '',
      assignedDepartment: '',
      assignedRoom: '',
      status: 'Additional Documents Required',
      queueToken: '',
      estimatedTime: '',
      requestedAt: '2026-08-19T14:00:00.000Z',
      reviewedAt: '2026-08-19T16:00:00.000Z',
      supportingFiles: [],
      requestedDocuments: ['Prior Brain CT / MRI Scan Report', 'Official Hospital Discharge Summary', 'Patient National ID / Kebele ID'],
      adminNote: 'Please provide the recent CT Scan and discharge summary before we can assign an orthopedic specialist.',
    },
  ],

  queue: [
    {
      token: 'C-023',
      appointmentId: 'APT-1001',
      patientId: 'HF-0247',
      patientName: 'Ahmed Kamara',
      department: 'Cardiology Clinic',
      roomNumber: 'Room 104',
      assignedDoctor: 'Dr. M. Worku',
      estimatedTime: '2026-08-25T09:00:00.000Z',
      durationMinutes: 10,
      status: 'Scheduled',
      urgency: 'High',
      orderIndex: 0,
      requiredDocuments: ['Medical Records', 'ID / QR Card', 'Lab Reports'],
    },
    {
      token: 'C-024',
      appointmentId: 'APT-1003',
      patientId: 'HF-0312',
      patientName: 'Selamawit Tadesse',
      department: 'General Surgery Clinic',
      roomNumber: 'Room 202',
      assignedDoctor: 'Dr. Tadesse Bekele',
      estimatedTime: '2026-08-25T09:10:00.000Z',
      durationMinutes: 10,
      status: 'Waiting',
      urgency: 'Emergency',
      orderIndex: 1,
      requiredDocuments: ['Medical Records', 'ID / QR Card'],
    },
    {
      token: 'C-025',
      appointmentId: '',
      patientId: 'HF-0298',
      patientName: 'Solomon Haile',
      department: 'Internal Medicine Clinic',
      roomNumber: 'Room 108',
      assignedDoctor: 'Dr. S. Alemu',
      estimatedTime: '2026-08-25T09:20:00.000Z',
      durationMinutes: 10,
      status: 'Waiting',
      urgency: 'Routine',
      orderIndex: 2,
      requiredDocuments: ['Patient ID / QR Card'],
    },
  ],

  financialCases: [
    {
      id: 'CASE-2026-8801',
      patientId: 'HF-0247',
      patientName: 'Ahmed Kamara',
      age: 42,
      location: 'Addis Ababa, Lideta',
      diagnosis: 'Severe Hypertensive Heart Failure & Valve Procedure',
      verifyingHospital: 'Zewditu Memorial Hospital',
      verifiedByDoctor: 'Dr. M. Worku (Head of Cardiology)',
      verificationStage1: 'Medical Records Verified at Zewditu Memorial Hospital',
      verificationStage2: 'Financial Need Verified by Zewditu Social Work Unit',
      targetAmount: 85000, // ETB
      raisedAmount: 54200, // ETB
      currency: 'ETB',
      description: 'Ahmed is a 42-year-old father of three suffering from acute hypertensive heart failure requiring specialized interventional cardiac care and medication support at Zewditu Memorial Hospital. His family cannot afford the specialized surgical supply costs.',
      status: 'Active',
      donorsCount: 142,
      hospitalBadgeUrl: '/badges/zewditu_verified.png',
      createdAt: '2026-08-11T16:00:00Z',
    },
    {
      id: 'CASE-2026-8805',
      patientId: 'HF-0389',
      patientName: 'Tigist Mersha',
      age: 8,
      location: 'Adama, Oromia',
      diagnosis: 'Pediatric Ventricular Septal Defect Repair',
      verifyingHospital: 'Zewditu Memorial Hospital',
      verifiedByDoctor: 'Dr. Abera Tekle',
      verificationStage1: 'Medical Records Verified at Zewditu Memorial Hospital',
      verificationStage2: 'Financial Assistance Approved',
      targetAmount: 120000,
      raisedAmount: 98500,
      currency: 'ETB',
      description: 'Tigist is an 8-year-old student referred for congenital heart defect corrective surgery. The medical team at Zewditu has cleared her for surgery upon funding verification.',
      status: 'Active',
      donorsCount: 310,
      createdAt: '2026-08-05T10:00:00Z',
    },
  ],

  users: {
    'you@example.com': {
      name: 'Ahmed Kamara',
      email: 'you@example.com',
      password: 'password123',
      age: 42,
      gender: 'Male',
      location: 'Addis Ababa, Lideta',
      patientId: 'HF-0247',
      status: 'Verified',
      registered: '12 Aug 2026',
    },
    'staff@zewditu.gov.et': {
      name: 'Dr. Tadesse Bekele',
      email: 'staff@zewditu.gov.et',
      password: 'hospital123',
      hospitalId: 'HOSP-001',
      hospitalName: 'Zewditu Memorial Hospital',
      role: 'Hospital Officer',
    },
    'admin@zewditu.gov.et': {
      name: 'Dr. M. Worku',
      email: 'admin@zewditu.gov.et',
      password: 'admin123',
      hospitalId: 'HOSP-001',
      hospitalName: 'Zewditu Memorial Hospital',
      role: 'Head of Department',
    },
  },

  messages: [
    {
      id: 'MSG-1001',
      name: 'Selamawit Desta',
      contact: 'selam.desta@gmail.com',
      category: 'Medical File Verification',
      message: 'Hello, I uploaded my medical lab results and doctor certificate yesterday for Zewditu Memorial Hospital. Could you please check the verification status so I can confirm my appointment?',
      status: 'Unread',
      createdAt: '2026-08-15T09:20:00Z',
    },
    {
      id: 'MSG-1002',
      name: 'Kassahun Belay',
      contact: 'kassahun.b@ethionet.et',
      category: 'Medical File Verification',
      message: 'Inquiring about medical file review timeline at Zewditu Memorial Hospital Cardiology clinic.',
      status: 'Read',
      createdAt: '2026-08-14T14:45:00Z',
    },
    {
      id: 'MSG-1003',
      name: 'Genet Wolde',
      contact: 'genet.w@yahoo.com',
      category: 'Community Agent',
      message: 'My elderly mother cannot travel easily to the hospital or use a smartphone. We would appreciate a community health field agent visit in Kirkos / Lideta area.',
      status: 'Unread',
      createdAt: '2026-08-15T11:10:00Z',
    },
  ],

  // System admins (separate from hospital users)
  admins: {
    'superadmin@healfund.et': {
      name: 'HealFund Administrator',
      email: 'superadmin@healfund.et',
      password: 'healfund@admin2026',
      role: 'superadmin',
      avatar: 'H',
    },
  },

  // Patient uploaded documents — only admin can view & verify
  patientDocuments: [
    {
      id: 'DOC-0001',
      patientId: 'HF-0247',
      patientName: 'Ahmed Kamara',
      originalName: 'ECG_Report_0247.pdf',
      filename: 'sample-ecg-report.pdf',
      size: '1.20 MB',
      type: 'pdf',
      category: 'Privacy & Diagnostic Report',
      isPrivacyDocument: true,
      uploadDate: '2026-08-12T08:30:00Z',
      status: 'Pending Verification', // 'Pending Verification' | 'Verified' | 'Rejected'
      adminNote: '',
      queueToken: null,
    },
    {
      id: 'DOC-0002',
      patientId: 'HF-0247',
      patientName: 'Ahmed Kamara',
      originalName: 'Lab_Results_Lideta.pdf',
      filename: 'sample-lab-results.pdf',
      size: '0.85 MB',
      type: 'pdf',
      category: 'Confidential Health File',
      isPrivacyDocument: true,
      uploadDate: '2026-08-12T08:35:00Z',
      status: 'Verified',
      adminNote: 'Lab values confirmed by Admin. Added to Zewditu Cardiology waiting list.',
      queueToken: 'C-023',
    },
    {
      id: 'DOC-0003',
      patientId: 'HF-0312',
      patientName: 'Bethlehem Alemu',
      originalName: 'Ultrasound_Report.pdf',
      filename: 'sample-ultrasound.pdf',
      size: '2.10 MB',
      type: 'pdf',
      category: 'Privacy & Imaging Record',
      isPrivacyDocument: true,
      uploadDate: '2026-08-13T10:00:00Z',
      status: 'Pending Verification',
      adminNote: '',
      queueToken: null,
    },
  ],

  // Activity log for audit trail
  activityLog: [
    {
      id: 'LOG-001',
      action: 'Appointment Confirmed',
      detail: 'APT-1001 confirmed for Ahmed Kamara at Zewditu Memorial Hospital',
      actor: 'Dr. M. Worku',
      timestamp: '2026-08-11T14:15:00Z',
    },
    {
      id: 'LOG-002',
      action: 'Financial Case Created',
      detail: 'CASE-2026-8801 opened for Ahmed Kamara',
      actor: 'System',
      timestamp: '2026-08-11T16:00:00Z',
    },
    {
      id: 'LOG-003',
      action: 'Donation Received',
      detail: 'CASE-2026-8801 received 500 ETB donation',
      actor: 'Anonymous Donor',
      timestamp: '2026-08-12T09:20:00Z',
    },
  ],
};
